version: "3"

services:
  app:
    build:
      context: app
      args:
        version: 0.0.0
    environment:
      - KESTREL__ENDPOINTS__HTTP__URL=http://*:5000
      - MONGODB__CONNECTIONSTRING=mongodb://mongo:27017/demo
      - ASPNETCORE_ENVIRONMENT=Compose
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2

  outside-in.tests:
    build:
      context: outside-in.tests
    environment:
      - APP_URI=http://app:5000/
    depends_on:
      - app
