version: "3"

services:
  app:
    build:
      context: app
      args:
        version: 0.0.0
    environment:
      - KESTREL__ENDPOINTS__HTTP__URL=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Compose

  outside-in.tests:
    build:
      context: outside-in.tests
    environment:
      - APP_URI=http://app:5000/
    depends_on:
      - app
